services:

  telegram_logic:
    build:
      context: .
      dockerfile: telegram_logic/Dockerfile

    container_name: telegram_logic

    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      DB__NAME: database
      DB__HOST: database
      DB__PORT: "5432"

    env_file:
      - .env

    volumes:
      - ./telegram_logic:/app
      - ./packages/kb_schemas:/packages/kb_schemas

    depends_on:
      database:
        condition: service_healthy
 

  database:
    build:
      context: .
      dockerfile: database/Dockerfile

    container_name: database

    environment:
     - PYTHONDONTWRITEBYTECODE=1

    ports:
      - "5432:5432"
    volumes:
      - ./database:/app
      - ./packages/kb_schemas:/packages/kb_schemas

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://127.0.0.1:5432/docs')"
        ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s